import "./globals.css";
import MainNavbar from "./navbar/MainNavigation";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <MainNavbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
